name: Publish Markdown to WordPress

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "content/**/*.md"
      - "content/**/*.{png,jpg,jpeg,webp}"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: action

    steps:
      - name: Network debug
        run: |
          ping -c 4 blog.a42n.com || true
          nslookup blog.a42n.com || true
          curl -I https://blog.a42n.com || true
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install markdown PyYAML requests python-frontmatter dotenv

      - name: Run WordPress Publisher
        env:
          WP_BASE_URL: ${{ vars.WP_BASE_URL }}
          WP_USER: ${{ vars.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
        run: |
          python scripts/publish.py
